name: Deploy the release bot to AWS

on:
  #push: 
  #  branches: 
  #    -main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3.0.0
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEPLOYER_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEPLOYER_ACCESS_SECRET_KEY }}
        aws-region: eu-west-2
    - name: Run the deploy script
      run: |
        swift ./deploy/deploy.swift
      #env:
      #  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_ACCESS_KEY_ID }}
      #  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_ACCESS_SECRET_KEY }}
      #  AWS_DEFAULT_REGION: eu-west-2
        
    
